name: frpc-arm32v7
on:
  push:
    branches:
    - master 
    tags:
      - '*'
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: frpc/arm32v7
          platforms: linux/arm/v7
          push: true
          tags: |
            ghcr.io/mjmenger/frpc:arm32v7-latest
            ghcr.io/mjmenger/frpc:arm32v7-0.58.1            
