name: frps-amd64
on:
  push:
    branches:
      - master  
    tags:
      - '*'
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: frps/amd64
          platforms: linux/amd64
          push: true
          tags: |
            mmengeramd64/frps:latest
            mmengeramd64/frps:0.58.1
            ghcr.io/mjmenger/frps:amd64-latest
            ghcr.io/mjmenger/frps:amd64-0.58.1            
